# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmdStartSlideshow = QtWidgets.QPushButton(self.centralwidget)
        self.cmdStartSlideshow.setGeometry(QtCore.QRect(470, 240, 241, 41))
        self.cmdStartSlideshow.setObjectName("cmdStartSlideshow")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 61))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.cmdSettings = QtWidgets.QPushButton(self.centralwidget)
        self.cmdSettings.setGeometry(QtCore.QRect(470, 400, 241, 41))
        self.cmdSettings.setObjectName("cmdSettings")
        self.lblSlideshow = QtWidgets.QLabel(self.centralwidget)
        self.lblSlideshow.setGeometry(QtCore.QRect(250, 250, 201, 20))
        self.lblSlideshow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSlideshow.setObjectName("lblSlideshow")
        self.lblSettings = QtWidgets.QLabel(self.centralwidget)
        self.lblSettings.setGeometry(QtCore.QRect(300, 410, 151, 17))
        self.lblSettings.setTextFormat(QtCore.Qt.AutoText)
        self.lblSettings.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSettings.setObjectName("lblSettings")
        self.cmdStartSlideshow_2 = QtWidgets.QPushButton(self.centralwidget)
        self.cmdStartSlideshow_2.setGeometry(QtCore.QRect(470, 320, 241, 41))
        self.cmdStartSlideshow_2.setObjectName("cmdStartSlideshow_2")
        self.lblDownloadImages = QtWidgets.QLabel(self.centralwidget)
        self.lblDownloadImages.setGeometry(QtCore.QRect(250, 330, 201, 20))
        self.lblDownloadImages.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDownloadImages.setObjectName("lblDownloadImages")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cmdStartSlideshow.setText(_translate("MainWindow", "Start Slideshow"))
        self.label.setText(_translate("MainWindow", "Picturebox"))
        self.cmdSettings.setText(_translate("MainWindow", "Settings..."))
        self.lblSlideshow.setText(_translate("MainWindow", "Start displaying pictures"))
        self.lblSettings.setText(_translate("MainWindow", "Set up the application"))
        self.cmdStartSlideshow_2.setText(_translate("MainWindow", "Manually Download Images"))
        self.lblDownloadImages.setText(_translate("MainWindow", "Download images"))
